version: "3"
services:
  hub:
    image: selenium/hub:4.16
  chrome:
    image: selenium/node-chromium:4.16
    shm_size: '2g'
    depends_on:
    - hub
    deploy:
      replicas: 0
    env_file: .env
  firefox:
    image: selenium/node-firefox:4.16
    shm_size: '2g'
    depends_on:
    - hub
    deploy:
      replicas: 0
    env_file: .env